version: '3'

services:
    nginx:
        build: ./nginx
        restart: always
        depends_on: 
            - node
        ports:
            - "80:80"
    node:
        build: ./node
        expose:
            - "3000"
